# Generated by Django 2.0.5 on 2018-05-24 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=25)),
                ('text', models.TextField(blank=True, max_length=1000)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NextMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=1000)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('graduate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.Graduate')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_as', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=40)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Graduate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Job')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Major')),
                ('next_major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.NextMajor')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Parent')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.SchoolType'),
        ),
        migrations.AddField(
            model_name='person',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.School'),
        ),
        migrations.AddField(
            model_name='outbox',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.Person'),
        ),
        migrations.AddField(
            model_name='outbox',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.School'),
        ),
        migrations.AddField(
            model_name='outbox',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.MessageStatus'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.MessageStatus'),
        ),
    ]
